---
abstract: 'Perl-Net-Douban based on Moose and XML::Atom'
author:
  - woosley.xu
generated_by: 'Dist::Zilla version 1.100160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Net-Douban
requires:
  ExtUtils::MakeMaker: 6.11
  HTTP::Request: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Moose: 0.81
  Net::OAuth: 0
  Scalar::Util: 0
  XML::Atom: 0.35
version: 0.41
